apiVersion: v1  
kind: Service                                 
metadata:
  name: todo-service               
  labels:                                     
    app: todo-service
spec:
  type: NodePort                              
  selector:
    app: todo-service               
  ports: 
  - name: http
    port: 8080
    targetPort: 8080