
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: todo
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: '123456789'
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: '5432' 